---
title: "Research"
anchor-sections: false
---

My research interestes lie in in the field of empirical IO applied to energy and environmental economics. Specifically, I study the role of power market design in the energy transition with a primary focus on locational and real-time pricing. Other interests include industrial decarbonisation, climate policy and international economics. 


## Work in Progress

Unlocking households’ flexibility potential - on
the barriers to real-time pricing

## Pre-PhD Publications

Böschemeier, J., & Jochem, A. (2024). The effect of foreign carbon prices on German outward FDI. *Economics Letters*, 234, 111499. [Link](https://www.sciencedirect.com/science/article/pii/S0165176523005256)

Böschemeier, J., & Mau, K. (2023). Foreign supply shocks and the structure of trade in a small open economy. *De Economist*, 171(4), 303-342. [Link](https://link.springer.com/article/10.1007/s10645-023-09425-z)



## Non-refereed Publications

Böschemeier, J. and Mau, K. (2022). Gediversifieerd netwerk van handelspartners helpt
schokken op te vangen. *Economisch Statistische Berichten*, 107(4816):542–544.  [Link](https://esb.nu/gediversifieerd-netwerk-van-handelspartners-helpt-schokken-op-te-vangen/#:~:text=We%20laten%20zien%20dat%20industrie%C3%ABn,te%20verminderen%20in%20onzekere%20tijden.) (Dutch)


Böschemeier, J., Teti, F., Cernicky, J., and Moncayo, G. R. (2022). AfCFTA in a Rut –
Can the Pan-African Agreement Regain Momentum? *CESifo Forum*, 23(02):46–57. [Link](https://www.cesifo.org/en/publications/2022/article-journal/afcfta-rut-can-pan-african-agreement-regain-momentum)


Böschemeier, J. and Teti, F. (2021). Die panafrikanische Freihandelszone AfCFTA–Utopie
oder reale Chance? *ifo Schnelldienst*, 74(10):50–61. [Link](https://www.ifo.de/publikationen/2021/aufsatz-zeitschrift/die-panafrikanische-freihandelszone-afcfta-utopie-oder-reale6)
 (German) 

